plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"window-to-reality" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	compileOnly "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

afterEvaluate {
	loom.runs.configureEach {
		vmArgs(
			"-Xmx4G",
			"-XX:+AllowEnhancedClassRedefinition",
			"-XX:ReservedCodeCacheSize=1G",
			"-javaagent:${ configurations.compileClasspath.find { it.name.contains("sponge-mixin") } }",
			"-DMC_DEBUG_ENABLED",
			"-DMC_DEBUG_PREFER_WAYLAND",
		)
	}
}

apply from: 'package-info.gradle'

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}