name: build
on: [pull_request, push]

jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: checkout repository
              uses: actions/checkout@v6
            - name: validate gradle wrapper
              uses: gradle/actions/wrapper-validation@v6
            - name: setup jdk
              uses: actions/setup-java@v5
              with:
                  java-version: "25"
                  distribution: "microsoft"
            - name: make gradle wrapper executable
              run: chmod +x ./gradlew
            - name: build
              run: ./gradlew build
            - name: attest build provenance
              uses: actions/attest-build-provenance@v2
              with:
                  subject-path: "build/libs/*.jar, !build/libs/*-sources.jar"
            - name: artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Artifacts
                  path: |
                      build/libs/*.jar
                      !build/libs/*-sources.jar
            - name: publish
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-id: xW3OImaS
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
